# -*- coding: utf-8 -*-
"""email-response-rag-system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/190b8mb2MU3uRYeUZle2A-IkLJZkoWdb8
"""

# ================== Install dependencies in Colab ==================
!pip install -q langchain langchain-openai langchain-groq langchain_community langchain-huggingface faiss-cpu pandas openpyxl sentence-transformers
#!pip install -q langchain langchain_openai faiss-cpu openpyxl pandas langchain-groq
#!pip install -q langchain langchain-community langchain-groq


import pandas as pd
import os
#from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_community.vectorstores import FAISS   # ✅ updated import

# import pandas as pd
# from langchain_openai import OpenAIEmbeddings, ChatOpenAI
# from langchain_groq import ChatGroq
# from langchain.prompts import ChatPromptTemplate
# from langchain.vectorstores import FAISS
# import os

# ================== STEP 1: Load dataset ==================
products = pd.read_excel("/content/Product_Email_Dataset.xlsx", sheet_name="Products")
emails = pd.read_excel("/content/Product_Email_Dataset.xlsx", sheet_name="Client Emails")

print("Products:")
print(products.head())

# ================== STEP 2: Create Vectorstore of product descriptions ==================
#embeddings = OpenAIEmbeddings(model="text-embedding-3-small")
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

# Convert products into documents for retrieval
product_texts = [
    f"Product: {row['Name']}. {row['Description']}. Season: {row['Seasons']}. Price: {row['Price']}. Stock: {row['Stock']}"
    for _, row in products.iterrows()
]

vectorstore = FAISS.from_texts(product_texts, embeddings)

# ================== STEP 3: LLM initialization ==================

# os.environ["GROQ_API_KEY"] = "GROQ_API_KEY_HERE"
# llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0)
llm = ChatGroq(
    model="llama-3.1-8b-instant",
    api_key=os.getenv("GROQ_API_KEY"),
    temperature=0
)
#llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.3)

prompt_template = ChatPromptTemplate.from_template(
    """
    You are a helpful customer support assistant.

    Customer email:
    {email_text}

    Retrieved products from database:
    {retrieved_products}

    Instructions:
    - ONLY use the retrieved products to answer.
    - DO NOT make up any products.
    - If no relevant product is found, clearly say: "Sorry, this product is not available in our database."
    - If product exists, provide correct price and stock.
    - If email is unrelated, give a general polite response.
    """
)

# ================== STEP 4: Response generation with retrieval ==================
def generate_response(email_subject, email_body, top_k=3):
    email_text = (email_subject or "") + " " + (email_body or "")

    # # Exact match check (very important)
    # for _, row in products.iterrows():
    #     product_name = str(row['Name']).lower()
    #     if product_name in email_text.lower():
    #         return f"""
    # Subject: Re: Product Inquiry

    # Dear Customer,

    # The product "{row['Name']}" is available.

    # Price: ${row['Price']}
    # Stock: {row['Stock']} units

    # Let us know if you'd like to place an order.

    # Best regards,
    # Customer Support
    # """

    # Retrieve most relevant products
    docs_with_scores = vectorstore.similarity_search_with_score(email_text, k=top_k)

    # Filter relevant results only
    filtered_docs = [doc for doc, score in docs_with_scores if score < 1.0]

    if not filtered_docs:
        retrieved_products = "No relevant product found"
    else:
        retrieved_products = "\n".join([doc.page_content for doc in filtered_docs])

    chain = prompt_template | llm
    response = chain.invoke({"email_text": email_text, "retrieved_products": retrieved_products})
    return response.content

# ================== STEP 5: Test ==================
sample = emails.sample(5)
for _, row in sample.iterrows():
    print("\nEmail:", row["email_subject"], row["email_body"])
    print("Response:", generate_response(row["email_subject"], row["email_body"]))

print(products['Name'].unique())

